[2025-08-22T00:00:27.704+0000] {processor.py:157} INFO - Started process (PID=864) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:00:27.705+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:00:27.705+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:00:27.705+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:00:29.041+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:00:29.040+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:00:29.041+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:00:29.048+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.346 seconds
[2025-08-22T00:00:59.315+0000] {processor.py:157} INFO - Started process (PID=885) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:00:59.316+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:00:59.317+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:00:59.317+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:01:00.678+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:01:00.677+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:01:00.678+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:01:00.686+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.374 seconds
[2025-08-22T00:01:30.927+0000] {processor.py:157} INFO - Started process (PID=906) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:01:30.928+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:01:30.929+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:01:30.929+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:01:32.507+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:01:32.507+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:01:32.508+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:01:32.515+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.593 seconds
[2025-08-22T00:02:02.744+0000] {processor.py:157} INFO - Started process (PID=927) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:02:02.745+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:02:02.746+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:02:02.746+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:02:04.194+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:02:04.193+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:02:04.194+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:02:04.202+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.460 seconds
[2025-08-22T00:02:34.463+0000] {processor.py:157} INFO - Started process (PID=948) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:02:34.464+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:02:34.465+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:02:34.465+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:02:35.944+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:02:35.943+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:02:35.944+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:02:35.952+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.494 seconds
[2025-08-22T00:03:06.227+0000] {processor.py:157} INFO - Started process (PID=969) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:03:06.228+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:03:06.229+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:03:06.228+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:03:07.904+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:03:07.903+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:03:07.904+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:03:07.911+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.689 seconds
[2025-08-22T00:03:38.147+0000] {processor.py:157} INFO - Started process (PID=990) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:03:38.148+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:03:38.149+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:03:38.149+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:03:39.547+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:03:39.546+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:03:39.547+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:03:39.554+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.410 seconds
[2025-08-22T00:04:09.822+0000] {processor.py:157} INFO - Started process (PID=1011) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:04:09.824+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:04:09.825+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:04:09.824+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:04:11.291+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:04:11.290+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:04:11.291+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:04:11.297+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.477 seconds
[2025-08-22T00:04:41.542+0000] {processor.py:157} INFO - Started process (PID=1032) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:04:41.543+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:04:41.543+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:04:41.543+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:04:42.890+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:04:42.889+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:04:42.890+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:04:42.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.357 seconds
[2025-08-22T00:05:13.168+0000] {processor.py:157} INFO - Started process (PID=1053) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:05:13.169+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:05:13.170+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:05:13.169+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:05:14.613+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:05:14.612+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:05:14.613+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:05:14.620+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.456 seconds
[2025-08-22T00:05:44.905+0000] {processor.py:157} INFO - Started process (PID=1074) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:05:44.906+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:05:44.907+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:05:44.906+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:05:46.470+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:05:46.469+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:05:46.470+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:05:46.477+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.577 seconds
[2025-08-22T00:06:16.631+0000] {processor.py:157} INFO - Started process (PID=1095) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:06:16.632+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:06:16.633+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:06:16.633+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:06:18.049+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:06:18.048+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:06:18.049+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:06:18.057+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.428 seconds
[2025-08-22T00:06:48.319+0000] {processor.py:157} INFO - Started process (PID=1116) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:06:48.320+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:06:48.321+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:06:48.321+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:06:49.697+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:06:49.696+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:06:49.697+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:06:49.704+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.388 seconds
[2025-08-22T00:07:20.004+0000] {processor.py:157} INFO - Started process (PID=1137) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:07:20.005+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:07:20.006+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:07:20.006+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:07:21.835+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:07:21.834+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:07:21.836+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:07:21.845+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.845 seconds
[2025-08-22T00:07:52.058+0000] {processor.py:157} INFO - Started process (PID=1158) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:07:52.059+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:07:52.059+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:07:52.059+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:07:53.533+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:07:53.532+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:07:53.533+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:07:53.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.485 seconds
[2025-08-22T00:08:23.816+0000] {processor.py:157} INFO - Started process (PID=1179) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:08:23.817+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:08:23.818+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:08:23.818+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:08:25.163+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:08:25.162+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:08:25.163+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:08:25.170+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.358 seconds
[2025-08-22T00:08:55.429+0000] {processor.py:157} INFO - Started process (PID=1200) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:08:55.429+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:08:55.430+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:08:55.430+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:08:56.939+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:08:56.938+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:08:56.941+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:08:56.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.526 seconds
[2025-08-22T00:09:27.199+0000] {processor.py:157} INFO - Started process (PID=1221) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:09:27.200+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:09:27.201+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:09:27.200+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:09:28.691+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:09:28.691+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:09:28.692+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:09:28.699+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.504 seconds
[2025-08-22T00:09:58.924+0000] {processor.py:157} INFO - Started process (PID=1242) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:09:58.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:09:58.925+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:09:58.925+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:10:00.250+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:10:00.249+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:10:00.250+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:10:00.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.336 seconds
[2025-08-22T00:10:30.511+0000] {processor.py:157} INFO - Started process (PID=1263) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:10:30.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:10:30.512+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:10:30.512+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:10:31.849+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:10:31.849+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:10:31.850+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:10:31.857+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.349 seconds
[2025-08-22T00:11:02.133+0000] {processor.py:157} INFO - Started process (PID=1284) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:11:02.134+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:11:02.135+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:11:02.135+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:11:03.480+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:11:03.479+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:11:03.480+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:11:03.487+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.357 seconds
[2025-08-22T00:11:33.737+0000] {processor.py:157} INFO - Started process (PID=1305) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:11:33.738+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:11:33.739+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:11:33.739+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:11:35.057+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:11:35.056+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:11:35.057+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:11:35.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.329 seconds
[2025-08-22T00:12:05.334+0000] {processor.py:157} INFO - Started process (PID=1326) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:12:05.335+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:12:05.336+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:12:05.335+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:12:06.743+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:12:06.742+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:12:06.743+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:12:06.750+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.420 seconds
[2025-08-22T00:12:37.020+0000] {processor.py:157} INFO - Started process (PID=1347) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:12:37.021+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:12:37.021+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:12:37.021+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:12:38.419+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:12:38.418+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:12:38.419+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:12:38.426+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.409 seconds
[2025-08-22T00:13:08.680+0000] {processor.py:157} INFO - Started process (PID=1368) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:13:08.681+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:13:08.682+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:13:08.681+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:13:10.177+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:13:10.176+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:13:10.177+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:13:10.185+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.509 seconds
[2025-08-22T00:13:40.440+0000] {processor.py:157} INFO - Started process (PID=1389) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:13:40.440+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:13:40.441+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:13:40.441+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:13:41.857+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:13:41.856+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:13:41.857+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:13:41.865+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.429 seconds
[2025-08-22T00:14:12.091+0000] {processor.py:157} INFO - Started process (PID=1410) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:14:12.092+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:14:12.093+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:14:12.092+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:14:13.507+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:14:13.506+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:14:13.507+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:14:13.514+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.427 seconds
[2025-08-22T00:14:43.780+0000] {processor.py:157} INFO - Started process (PID=1431) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:14:43.780+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:14:43.781+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:14:43.781+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:14:45.363+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:14:45.362+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:14:45.363+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:14:45.371+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.595 seconds
[2025-08-22T00:15:15.607+0000] {processor.py:157} INFO - Started process (PID=1452) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:15:15.608+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:15:15.608+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:15:15.608+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:15:17.033+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:15:17.032+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:15:17.033+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:15:17.040+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.435 seconds
[2025-08-22T00:15:47.287+0000] {processor.py:157} INFO - Started process (PID=1473) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:15:47.288+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:15:47.289+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:15:47.288+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:15:48.629+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:15:48.629+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:15:48.630+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:15:48.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.354 seconds
[2025-08-22T00:16:18.895+0000] {processor.py:157} INFO - Started process (PID=1494) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:16:18.896+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:16:18.897+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:16:18.896+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:16:20.626+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:16:20.625+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:16:20.626+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:16:20.634+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.744 seconds
[2025-08-22T00:16:50.730+0000] {processor.py:157} INFO - Started process (PID=1515) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:16:50.731+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:16:50.732+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:16:50.731+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:16:52.157+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:16:52.156+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:16:52.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:16:52.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.437 seconds
[2025-08-22T00:17:22.447+0000] {processor.py:157} INFO - Started process (PID=1536) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:17:22.448+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:17:22.448+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:17:22.448+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:17:23.878+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:17:23.877+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:17:23.878+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:17:23.888+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.445 seconds
[2025-08-22T00:17:54.179+0000] {processor.py:157} INFO - Started process (PID=1557) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:17:54.180+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:17:54.181+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:17:54.181+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:17:55.751+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:17:55.750+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:17:55.751+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:17:55.758+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.583 seconds
[2025-08-22T00:18:25.948+0000] {processor.py:157} INFO - Started process (PID=1578) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:18:25.949+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:18:25.950+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:18:25.950+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:18:27.268+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:18:27.268+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:18:27.269+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:18:27.275+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.330 seconds
[2025-08-22T00:18:57.516+0000] {processor.py:157} INFO - Started process (PID=1599) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:18:57.517+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:18:57.517+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:18:57.517+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:18:58.878+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:18:58.877+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:18:58.878+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:18:58.885+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.371 seconds
[2025-08-22T00:19:29.117+0000] {processor.py:157} INFO - Started process (PID=1620) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:19:29.118+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:19:29.119+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:19:29.118+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:19:30.484+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:19:30.484+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:19:30.485+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:19:30.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.377 seconds
[2025-08-22T00:20:00.778+0000] {processor.py:157} INFO - Started process (PID=1641) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:20:00.779+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:20:00.780+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:20:00.779+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:20:02.155+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:20:02.154+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:20:02.155+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:20:02.162+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.387 seconds
[2025-08-22T00:20:32.412+0000] {processor.py:157} INFO - Started process (PID=1662) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:20:32.413+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:20:32.414+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:20:32.414+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:20:33.740+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:20:33.739+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:20:33.740+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:20:33.748+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.339 seconds
[2025-08-22T00:21:03.995+0000] {processor.py:157} INFO - Started process (PID=1683) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:21:03.996+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:21:03.997+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:21:03.997+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:21:05.420+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:21:05.419+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:21:05.420+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:21:05.428+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.438 seconds
[2025-08-22T00:21:35.681+0000] {processor.py:157} INFO - Started process (PID=1704) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:21:35.682+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:21:35.683+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:21:35.682+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:21:37.169+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:21:37.169+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:21:37.170+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:21:37.176+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.499 seconds
[2025-08-22T00:22:07.390+0000] {processor.py:157} INFO - Started process (PID=1725) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:22:07.390+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:22:07.391+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:22:07.391+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:22:08.987+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:22:08.986+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:22:08.987+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:22:08.997+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.609 seconds
[2025-08-22T00:22:39.175+0000] {processor.py:157} INFO - Started process (PID=1746) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:22:39.176+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:22:39.176+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:22:39.176+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:22:40.541+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:22:40.540+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:22:40.541+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:22:40.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.368 seconds
[2025-08-22T00:23:10.826+0000] {processor.py:157} INFO - Started process (PID=1767) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:23:10.828+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:23:10.829+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:23:10.828+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:23:12.659+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:23:12.658+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:23:12.659+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:23:12.669+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.847 seconds
[2025-08-22T00:23:42.754+0000] {processor.py:157} INFO - Started process (PID=1788) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:23:42.755+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:23:42.756+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:23:42.756+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:23:44.080+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:23:44.080+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:23:44.081+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:23:44.087+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.336 seconds
[2025-08-22T00:24:14.148+0000] {processor.py:157} INFO - Started process (PID=1809) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:24:14.149+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:24:14.150+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:24:14.150+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:24:15.931+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:24:15.930+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:24:15.957+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:24:15.977+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.834 seconds
[2025-08-22T00:24:46.245+0000] {processor.py:157} INFO - Started process (PID=1830) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:24:46.248+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:24:46.248+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:24:46.248+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:24:47.714+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:24:47.713+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:24:47.715+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:24:47.722+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.486 seconds
[2025-08-22T00:25:17.846+0000] {processor.py:157} INFO - Started process (PID=1851) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:25:17.847+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:25:17.848+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:25:17.847+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:25:19.430+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:25:19.429+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:25:19.430+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:25:19.438+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.597 seconds
[2025-08-22T00:25:49.739+0000] {processor.py:157} INFO - Started process (PID=1872) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:25:49.739+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:25:49.740+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:25:49.740+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:25:51.290+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:25:51.289+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:25:51.290+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:25:51.298+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.563 seconds
[2025-08-22T00:26:21.396+0000] {processor.py:157} INFO - Started process (PID=1893) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:26:21.396+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:26:21.397+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:26:21.397+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:26:22.881+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:26:22.880+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:26:22.881+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:26:22.888+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.496 seconds
[2025-08-22T00:26:53.152+0000] {processor.py:157} INFO - Started process (PID=1914) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:26:53.153+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:26:53.154+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:26:53.154+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:26:54.810+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:26:54.810+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:26:54.811+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:26:54.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.670 seconds
[2025-08-22T00:27:25.011+0000] {processor.py:157} INFO - Started process (PID=1935) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:27:25.012+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:27:25.013+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:27:25.013+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:27:26.775+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:27:26.774+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:27:26.776+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:27:26.784+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.777 seconds
[2025-08-22T00:27:57.085+0000] {processor.py:157} INFO - Started process (PID=1956) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:27:57.086+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:27:57.087+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:27:57.086+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:27:58.662+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:27:58.661+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:27:58.662+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:27:58.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.590 seconds
[2025-08-22T00:28:28.954+0000] {processor.py:157} INFO - Started process (PID=1977) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:28:28.955+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:28:28.955+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:28:28.955+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:28:30.398+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:28:30.397+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:28:30.398+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:28:30.406+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.455 seconds
[2025-08-22T00:29:00.667+0000] {processor.py:157} INFO - Started process (PID=1998) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:29:00.668+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:29:00.668+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:29:00.668+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:29:02.116+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:29:02.115+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:29:02.117+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:29:02.125+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.461 seconds
[2025-08-22T00:29:32.381+0000] {processor.py:157} INFO - Started process (PID=2019) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:29:32.382+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:29:32.383+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:29:32.383+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:29:34.026+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:29:34.025+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:29:34.026+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:29:34.035+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.660 seconds
[2025-08-22T00:30:04.205+0000] {processor.py:157} INFO - Started process (PID=2040) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:30:04.206+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:30:04.207+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:30:04.207+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:30:05.698+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:30:05.697+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:30:05.698+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:30:05.706+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.504 seconds
[2025-08-22T00:30:35.936+0000] {processor.py:157} INFO - Started process (PID=2061) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:30:35.936+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:30:35.937+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:30:35.937+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:30:37.449+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:30:37.448+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:30:37.449+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:30:37.464+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.530 seconds
[2025-08-22T00:31:07.755+0000] {processor.py:157} INFO - Started process (PID=2082) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:31:07.756+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:31:07.757+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:31:07.756+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:31:09.384+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:31:09.383+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:31:09.384+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:31:09.392+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.641 seconds
[2025-08-22T00:31:39.639+0000] {processor.py:157} INFO - Started process (PID=2103) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:31:39.640+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:31:39.641+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:31:39.640+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:31:41.386+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:31:41.384+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:31:41.386+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:31:41.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.760 seconds
[2025-08-22T00:32:11.673+0000] {processor.py:157} INFO - Started process (PID=2124) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:32:11.674+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:32:11.675+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:32:11.675+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:32:13.362+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:32:13.361+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:32:13.362+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:32:13.369+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.700 seconds
[2025-08-22T00:32:43.421+0000] {processor.py:157} INFO - Started process (PID=2145) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:32:43.422+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:32:43.423+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:32:43.422+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:32:45.039+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:32:45.038+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:32:45.039+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:32:45.050+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.634 seconds
[2025-08-22T00:33:15.305+0000] {processor.py:157} INFO - Started process (PID=2166) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:33:15.306+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:33:15.307+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:33:15.307+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:33:16.840+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:33:16.839+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:33:16.841+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:33:16.848+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.549 seconds
[2025-08-22T00:33:47.078+0000] {processor.py:157} INFO - Started process (PID=2187) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:33:47.078+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:33:47.079+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:33:47.079+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:33:48.485+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:33:48.485+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:33:48.486+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:33:48.492+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.416 seconds
[2025-08-22T00:34:18.765+0000] {processor.py:157} INFO - Started process (PID=2208) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:34:18.766+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:34:18.768+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:34:18.767+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:34:20.487+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:34:20.486+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:34:20.487+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:34:20.496+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.735 seconds
[2025-08-22T00:34:50.573+0000] {processor.py:157} INFO - Started process (PID=2229) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:34:50.574+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:34:50.575+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:34:50.575+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:34:52.502+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:34:52.498+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:34:52.502+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:34:52.516+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.946 seconds
[2025-08-22T00:35:22.825+0000] {processor.py:157} INFO - Started process (PID=2250) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:35:22.826+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:35:22.827+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:35:22.826+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:35:24.614+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:35:24.613+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:35:24.614+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:35:24.621+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.802 seconds
[2025-08-22T00:35:54.890+0000] {processor.py:157} INFO - Started process (PID=2271) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:35:54.891+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:35:54.891+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:35:54.891+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:35:56.431+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:35:56.429+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:35:56.431+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:35:56.440+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.551 seconds
[2025-08-22T00:36:26.704+0000] {processor.py:157} INFO - Started process (PID=2292) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:36:26.705+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:36:26.706+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:36:26.705+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:36:28.158+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:36:28.157+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:36:28.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:36:28.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.465 seconds
[2025-08-22T00:36:58.427+0000] {processor.py:157} INFO - Started process (PID=2313) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:36:58.428+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:36:58.430+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:36:58.429+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:37:00.098+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:37:00.097+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:37:00.098+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:37:00.105+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.683 seconds
[2025-08-22T00:37:30.173+0000] {processor.py:157} INFO - Started process (PID=2334) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:37:30.173+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:37:30.174+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:37:30.173+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:37:31.914+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:37:31.913+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:37:31.914+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:37:31.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.751 seconds
[2025-08-22T00:38:02.202+0000] {processor.py:157} INFO - Started process (PID=2355) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:38:02.203+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:38:02.204+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:38:02.203+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:38:03.642+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:38:03.641+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:38:03.643+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:38:03.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.453 seconds
[2025-08-22T00:38:33.863+0000] {processor.py:157} INFO - Started process (PID=2376) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:38:33.864+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:38:33.865+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:38:33.864+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:38:35.338+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:38:35.338+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:38:35.339+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:38:35.346+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.487 seconds
[2025-08-22T00:39:05.549+0000] {processor.py:157} INFO - Started process (PID=2397) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:39:05.550+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:39:05.551+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:39:05.550+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:39:07.235+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:39:07.235+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:39:07.236+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:39:07.243+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.699 seconds
[2025-08-22T00:39:37.284+0000] {processor.py:157} INFO - Started process (PID=2418) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:39:37.285+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:39:37.286+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:39:37.285+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:39:38.760+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:39:38.759+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:39:38.761+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:39:38.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.489 seconds
[2025-08-22T00:40:08.991+0000] {processor.py:157} INFO - Started process (PID=2439) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:40:08.992+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:40:08.993+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:40:08.993+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:40:10.686+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:40:10.685+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:40:10.686+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:40:10.696+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.708 seconds
[2025-08-22T00:40:40.933+0000] {processor.py:157} INFO - Started process (PID=2460) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:40:40.933+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:40:40.934+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:40:40.934+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:40:42.379+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:40:42.378+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:40:42.379+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:40:42.386+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.456 seconds
[2025-08-22T00:41:12.632+0000] {processor.py:157} INFO - Started process (PID=2481) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:41:12.633+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:41:12.634+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:41:12.633+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:41:14.209+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:41:14.208+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:41:14.210+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:41:14.216+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.589 seconds
[2025-08-22T00:41:44.422+0000] {processor.py:157} INFO - Started process (PID=2502) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:41:44.422+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:41:44.423+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:41:44.423+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:41:46.052+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:41:46.051+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:41:46.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:41:46.066+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.648 seconds
[2025-08-22T00:42:16.290+0000] {processor.py:157} INFO - Started process (PID=2523) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:42:16.291+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:42:16.292+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:42:16.291+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:42:18.092+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:42:18.091+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:42:18.092+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:42:18.101+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.814 seconds
[2025-08-22T00:42:48.360+0000] {processor.py:157} INFO - Started process (PID=2544) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:42:48.361+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:42:48.362+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:42:48.362+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:42:49.906+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:42:49.906+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:42:49.907+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:42:49.914+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.558 seconds
[2025-08-22T00:43:20.168+0000] {processor.py:157} INFO - Started process (PID=2565) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:43:20.170+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:43:20.171+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:43:20.170+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:43:21.681+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:43:21.680+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:43:21.681+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:43:21.687+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.524 seconds
[2025-08-22T00:43:51.889+0000] {processor.py:157} INFO - Started process (PID=2586) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:43:51.890+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:43:51.891+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:43:51.890+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:43:53.565+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:43:53.564+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:43:53.566+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:43:53.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.689 seconds
[2025-08-22T00:44:23.831+0000] {processor.py:157} INFO - Started process (PID=2607) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:44:23.832+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:44:23.833+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:44:23.832+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:44:25.328+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:44:25.327+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:44:25.329+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:44:25.336+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.510 seconds
[2025-08-22T00:44:55.575+0000] {processor.py:157} INFO - Started process (PID=2628) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:44:55.576+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:44:55.576+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:44:55.576+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:44:57.073+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:44:57.072+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:44:57.074+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:44:57.088+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.516 seconds
[2025-08-22T00:45:27.342+0000] {processor.py:157} INFO - Started process (PID=2649) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:45:27.343+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:45:27.344+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:45:27.344+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:45:29.006+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:45:29.005+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:45:29.006+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:45:29.013+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.675 seconds
[2025-08-22T00:45:59.236+0000] {processor.py:157} INFO - Started process (PID=2670) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:45:59.237+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:45:59.238+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:45:59.237+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:46:00.761+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:46:00.760+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:46:00.761+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:46:00.768+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.536 seconds
[2025-08-22T00:46:30.828+0000] {processor.py:157} INFO - Started process (PID=2691) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:46:30.829+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:46:30.830+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:46:30.830+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:46:32.553+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:46:32.552+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:46:32.553+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:46:32.562+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.736 seconds
[2025-08-22T00:47:02.792+0000] {processor.py:157} INFO - Started process (PID=2712) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:47:02.793+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:47:02.793+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:47:02.793+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:47:04.833+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:47:04.832+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:47:04.834+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:47:04.847+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 2.057 seconds
[2025-08-22T00:47:35.037+0000] {processor.py:157} INFO - Started process (PID=2733) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:47:35.038+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:47:35.039+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:47:35.039+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:47:36.555+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:47:36.554+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:47:36.555+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:47:36.563+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.530 seconds
[2025-08-22T00:48:06.790+0000] {processor.py:157} INFO - Started process (PID=2754) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:48:06.792+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:48:06.792+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:48:06.792+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:48:08.284+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:48:08.284+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:48:08.285+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:48:08.293+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.508 seconds
[2025-08-22T00:48:38.558+0000] {processor.py:157} INFO - Started process (PID=2775) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:48:38.559+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:48:38.560+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:48:38.559+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:48:40.282+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:48:40.282+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:48:40.283+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:48:40.290+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.735 seconds
[2025-08-22T00:49:10.495+0000] {processor.py:157} INFO - Started process (PID=2796) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:49:10.496+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:49:10.496+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:49:10.496+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:49:12.088+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:49:12.087+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:49:12.088+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:49:12.095+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.601 seconds
[2025-08-22T00:49:42.370+0000] {processor.py:157} INFO - Started process (PID=2817) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:49:42.371+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:49:42.371+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:49:42.371+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:49:43.864+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:49:43.864+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:49:43.865+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:49:43.872+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.506 seconds
[2025-08-22T00:50:14.129+0000] {processor.py:157} INFO - Started process (PID=2838) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:50:14.130+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:50:14.130+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:50:14.130+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:50:15.522+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:50:15.521+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:50:15.522+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:50:15.528+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.402 seconds
[2025-08-22T00:50:45.800+0000] {processor.py:157} INFO - Started process (PID=2859) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:50:45.802+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:50:45.803+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:50:45.802+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:50:47.473+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:50:47.472+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:50:47.473+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:50:47.482+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.687 seconds
[2025-08-22T00:51:17.646+0000] {processor.py:157} INFO - Started process (PID=2880) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:51:17.648+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:51:17.649+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:51:17.648+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:51:19.374+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:51:19.373+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:51:19.375+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:51:19.383+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.741 seconds
[2025-08-22T00:51:49.616+0000] {processor.py:157} INFO - Started process (PID=2901) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:51:49.616+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:51:49.617+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:51:49.617+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:51:51.365+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:51:51.364+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:51:51.366+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:51:51.377+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.764 seconds
[2025-08-22T00:52:21.537+0000] {processor.py:157} INFO - Started process (PID=2922) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:52:21.537+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:52:21.538+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:52:21.538+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:52:26.289+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:52:26.282+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:52:26.291+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:52:26.401+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 4.867 seconds
[2025-08-22T00:52:56.612+0000] {processor.py:157} INFO - Started process (PID=2943) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:52:56.613+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:52:56.614+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:52:56.614+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:52:58.576+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:52:58.575+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:52:58.576+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:52:58.583+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.975 seconds
[2025-08-22T00:53:28.876+0000] {processor.py:157} INFO - Started process (PID=2964) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:53:28.877+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:53:28.879+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:53:28.878+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:53:30.503+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:53:30.503+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:53:30.504+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:53:30.511+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.641 seconds
[2025-08-22T00:54:00.749+0000] {processor.py:157} INFO - Started process (PID=2985) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:54:00.750+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:54:00.750+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:54:00.750+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:54:02.223+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:54:02.222+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:54:02.223+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:54:02.230+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.485 seconds
[2025-08-22T00:54:32.527+0000] {processor.py:157} INFO - Started process (PID=3006) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:54:32.528+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:54:32.529+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:54:32.528+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:54:34.006+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:54:34.006+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:54:34.007+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:54:34.014+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.491 seconds
[2025-08-22T00:55:04.285+0000] {processor.py:157} INFO - Started process (PID=3027) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:55:04.286+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:55:04.287+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:55:04.287+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:55:05.715+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:55:05.714+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:55:05.716+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:55:05.722+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.439 seconds
[2025-08-22T00:55:36.000+0000] {processor.py:157} INFO - Started process (PID=3048) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:55:36.001+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:55:36.002+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:55:36.002+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:55:37.467+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:55:37.467+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:55:37.468+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:55:37.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.479 seconds
[2025-08-22T00:56:07.657+0000] {processor.py:157} INFO - Started process (PID=3069) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:56:07.658+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:56:07.659+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:56:07.659+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:56:09.104+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:56:09.103+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:56:09.105+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:56:09.111+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.457 seconds
[2025-08-22T00:56:39.424+0000] {processor.py:157} INFO - Started process (PID=3090) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:56:39.425+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:56:39.426+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:56:39.426+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:56:41.043+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:56:41.042+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:56:41.043+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:56:41.050+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.634 seconds
[2025-08-22T00:57:11.206+0000] {processor.py:157} INFO - Started process (PID=3111) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:57:11.207+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:57:11.208+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:57:11.207+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:57:12.741+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:57:12.740+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:57:12.741+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:57:12.748+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.548 seconds
[2025-08-22T00:57:43.036+0000] {processor.py:157} INFO - Started process (PID=3132) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:57:43.037+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:57:43.038+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:57:43.037+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:57:44.554+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:57:44.553+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:57:44.554+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:57:44.562+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.530 seconds
[2025-08-22T00:58:14.853+0000] {processor.py:157} INFO - Started process (PID=3153) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:58:14.854+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:58:14.855+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:58:14.855+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:58:16.383+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:58:16.382+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:58:16.383+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:58:16.390+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.541 seconds
[2025-08-22T00:58:46.679+0000] {processor.py:157} INFO - Started process (PID=3174) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:58:46.680+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:58:46.681+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:58:46.680+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:58:48.401+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:58:48.400+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:58:48.401+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:58:48.409+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.735 seconds
[2025-08-22T00:59:18.661+0000] {processor.py:157} INFO - Started process (PID=3195) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:59:18.662+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:59:18.663+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:59:18.662+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:59:20.182+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:59:20.182+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:59:20.183+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:59:20.192+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.536 seconds
[2025-08-22T00:59:50.462+0000] {processor.py:157} INFO - Started process (PID=3216) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:59:50.463+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T00:59:50.464+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:59:50.463+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:59:52.008+0000] {logging_mixin.py:151} INFO - [2025-08-22T00:59:52.007+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T00:59:52.008+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T00:59:52.015+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.556 seconds
[2025-08-22T01:00:39.774+0000] {processor.py:157} INFO - Started process (PID=171) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T01:00:39.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T01:00:39.776+0000] {logging_mixin.py:151} INFO - [2025-08-22T01:00:39.776+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T01:00:42.660+0000] {logging_mixin.py:151} INFO - [2025-08-22T01:00:42.659+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T01:00:42.661+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T01:00:42.669+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 2.901 seconds
[2025-08-22T01:01:12.966+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T01:01:12.967+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T01:01:12.968+0000] {logging_mixin.py:151} INFO - [2025-08-22T01:01:12.968+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T01:01:14.607+0000] {logging_mixin.py:151} INFO - [2025-08-22T01:01:14.606+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T01:01:14.607+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T01:01:14.616+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.659 seconds
[2025-08-22T01:01:44.905+0000] {processor.py:157} INFO - Started process (PID=213) to work on /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T01:01:44.906+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/crypto_ml_pipeline.py for tasks to queue
[2025-08-22T01:01:44.907+0000] {logging_mixin.py:151} INFO - [2025-08-22T01:01:44.906+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T01:01:46.583+0000] {logging_mixin.py:151} INFO - [2025-08-22T01:01:46.582+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/crypto_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 274, in <module>
    from ml.models.volatility_lstm import train_model_pipeline, setup_mlflow_environment
ModuleNotFoundError: No module named 'ml'
[2025-08-22T01:01:46.583+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_ml_pipeline.py
[2025-08-22T01:01:46.592+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/crypto_ml_pipeline.py took 1.689 seconds
