[2025-08-22T03:52:31.327+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_ml_pipeline.retrain_model manual__2025-08-22T03:47:13.602120+00:00 [queued]>
[2025-08-22T03:52:31.330+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_ml_pipeline.retrain_model manual__2025-08-22T03:47:13.602120+00:00 [queued]>
[2025-08-22T03:52:31.330+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-08-22T03:52:31.335+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): retrain_model> on 2025-08-22 03:47:13.602120+00:00
[2025-08-22T03:52:31.342+0000] {standard_task_runner.py:57} INFO - Started process 497 to run task
[2025-08-22T03:52:31.345+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_ml_pipeline', 'retrain_model', 'manual__2025-08-22T03:47:13.602120+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/crypto_ml_pipeline.py', '--cfg-path', '/tmp/tmpnbtpn3c9']
[2025-08-22T03:52:31.347+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask retrain_model
[2025-08-22T03:52:31.372+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_ml_pipeline.retrain_model manual__2025-08-22T03:47:13.602120+00:00 [running]> on host d163e699a6cf
[2025-08-22T03:52:31.399+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='crypto-mlops' AIRFLOW_CTX_DAG_ID='crypto_ml_pipeline' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T03:47:13.602120+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T03:47:13.602120+00:00'
[2025-08-22T03:52:31.435+0000] {logging_mixin.py:151} WARNING - 2025/08/22 03:52:31 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-08-22T03:52:31.440+0000] {logging_mixin.py:151} INFO - MLflow Run ID: c2950c0a69be4aad9b3d1e3ad90f493b
[2025-08-22T03:52:31.441+0000] {logging_mixin.py:151} INFO - ‚ùå Error durante el entrenamiento y registro del modelo: name 'df' is not defined
[2025-08-22T03:52:31.441+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 318, in retrain_model
    raise e
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 289, in retrain_model
    df,
NameError: name 'df' is not defined
[2025-08-22T03:52:31.445+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=crypto_ml_pipeline, task_id=retrain_model, execution_date=20250822T034713, start_date=20250822T035231, end_date=20250822T035231
[2025-08-22T03:52:31.450+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task retrain_model (name 'df' is not defined; 497)
[2025-08-22T03:52:31.481+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-22T03:52:31.491+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
